name: NPC
version: '${project.version}'
main: win.oreo.npc.Main
author: superoreo

commands:
  item:
    aliases:
      - 아이템
  npc:
    aliases:
      - shop
      - 상점
  account:
    aliases:
      - acc
      - 계좌
      - money
      - balance
  questnpc:
    aliases:
      - qnpc
  quest:
    aliases:
      - 퀘스트
  questplayer:
    aliases:
      - qplayer